/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as EditAssetIdImport } from './routes/edit.$assetId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditAssetIdRoute = EditAssetIdImport.update({
  id: '/edit/$assetId',
  path: '/edit/$assetId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/edit/$assetId': {
      id: '/edit/$assetId'
      path: '/edit/$assetId'
      fullPath: '/edit/$assetId'
      preLoaderRoute: typeof EditAssetIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit/$assetId': typeof EditAssetIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit/$assetId': typeof EditAssetIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/edit/$assetId': typeof EditAssetIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/edit/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edit/$assetId'
  id: '__root__' | '/' | '/edit/$assetId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditAssetIdRoute: typeof EditAssetIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditAssetIdRoute: EditAssetIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/edit/$assetId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/edit/$assetId": {
      "filePath": "edit.$assetId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
