name: "Tauri Build Test"

on:
  pull_request:
    branches:
      - main
      - pre-release
      - "develop"
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**.md"
      - "renovate.json"
      - ".vscode/**"
  push:
    paths-ignore:
      - "**.md"
      - "renovate.json"
      - ".vscode/**"
    branches:
      - "main"
      - "pre-release"
      - "develop"

jobs:
  test-tauri:
    name: Tauri Build Test
    timeout-minutes: 30
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest" # (Arm based macs / M1 and above)
          #   args: "--target aarch64-apple-darwin"

          # - platform: "macos-latest" # (Intel based macs)
          #   args: "--target x86_64-apple-darwin"

          # - platform: "ubuntu-22.04"
          #   args: ""

          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
        if: matrix.platform == 'ubuntu-22.04'

      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          install: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          prefix-key: "v0-rust-${{ runner.os }}"
          workspaces: "./src-backend -> target"

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install --frozen-lockfile

      - uses: tauri-apps/tauri-action@84b9d35b5fc46c1e45415bdb6144030364f7ebc5 # v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--no-bundle ${{ matrix.args }}"
