name: Cargo Test
on:
  push:
    paths:
      - "src-tauri/**"
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
    paths:
      - "src-tauri/**"

permissions:
  contents: read

jobs:
  test:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run Test
        working-directory: src-tauri
        run: cargo test --all-features
