name: Cargo Test
on:
  push:
    paths:
      - "src-tauri/**"
      - "changelog.json"
    branches:
      - "main"
      - "pre-release"
      - "develop"
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
    paths:
      - "src-tauri/**"
      - "changelog.json"

permissions:
  contents: read

jobs:
  test:
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run Test
        working-directory: src-tauri
        run: cargo test --all-features
