name: Cargo Test
on:
  push:
    paths:
      - "src-backend/**"
      - "changelog.json"
      - ".github/workflows/cargo-test.yml"
    branches:
      - "main"
      - "pre-release"
      - "develop"
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
    paths:
      - "src-backend/**"
      - "changelog.json"
      - ".github/workflows/cargo-test.yml"

permissions:
  contents: read

jobs:
  test:
    name: Run cargo test
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest" # (Arm based macs / M1 and above)
          #   args: "--target aarch64-apple-darwin"

          # - platform: "macos-latest" # (Intel based macs)
          #   args: "--target x86_64-apple-darwin"

          # - platform: "ubuntu-22.04"
          #   args: ""

          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: rui314/setup-mold@7344740a9418dcdcb481c7df83d9fbd1d5072d7d # v1
        if: matrix.platform == 'ubuntu-22.04'

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
        with:
          workspaces: "./src-backend -> target"

      - name: install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run Test
        working-directory: src-backend
        run: cargo test --all-features
