name: Cargo Test
on:
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
    paths:
      - "src-tauri/**"

permissions:
  contents: read

jobs:
  test:
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Run Test
        working-directory: src-tauri
        run: cargo test --all-features
