name: Code Style Test
on:
  push:
    paths-ignore:
      - "**.md"
      - "renovate.json"
    branches-ignore:
      - "main"
      - "pre-release"
  pull_request:
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build-test:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    name: Code Style Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 23
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: node --version
      - run: pnpm --version

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint
      - run: pnpm run type-check
