name: Locales Test
on:
  push:
    paths:
      - "src/locales/**"
      - ".github/workflows/locales-test.yml"
    branches:
      - "main"
      - "pre-release"
      - "develop"
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
    paths:
      - "src/locales/**"
      - ".github/workflows/locales-test.yml"

permissions:
  contents: read

jobs:
  test:
    name: Run Localization File Test
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            const { default: checkLocaleKeys } = await import('${{ github.workspace }}/.github/workflows/scripts/locales-test.js')
            return checkLocaleKeys()
