name: Locales Test
on:
  push:
    paths:
      - "src/locales/**"
      - ".github/workflows/locales-test.yml"
    branches:
      - "main"
      - "pre-release"
      - "develop"
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
    paths:
      - "src/locales/**"
      - ".github/workflows/locales-test.yml"

permissions:
  contents: read

jobs:
  test:
    name: Run Localization File Test
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const { default: checkLocaleKeys } = await import('${{ github.workspace }}/.github/workflows/scripts/locales-test.js')
            return checkLocaleKeys()
