name: Version Consistency Check
on:
  push:
    paths:
      - "package.json"
      - "src-backend/tauri/Cargo.toml"
      - "src-backend/tauri/tauri.conf.json"
      - ".github/workflows/version-check.yml"
    branches:
      - "main"
      - "pre-release"
      - "develop"
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
    paths:
      - "package.json"
      - "src-backend/tauri/Cargo.toml"
      - "src-backend/tauri/tauri.conf.json"
      - ".github/workflows/version-check.yml"

permissions:
  contents: read

jobs:
  test:
    name: Version Consistency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - id: package-json
        uses: mikefarah/yq@1187c954ec44c3a0e62c13ca7dc9dadc1ca80ae7 # v4.46.1
        with:
          cmd: yq -oy '.version' package.json
      - id: cargo-toml
        uses: mikefarah/yq@1187c954ec44c3a0e62c13ca7dc9dadc1ca80ae7 # v4.46.1
        with:
          cmd: yq -oy '.package.version' src-backend/tauri/Cargo.toml
      - id: tauri-conf-json
        uses: mikefarah/yq@1187c954ec44c3a0e62c13ca7dc9dadc1ca80ae7 # v4.46.1
        with:
          cmd: yq -oy '.version' src-backend/tauri/tauri.conf.json
      - name: Check Version Consistency
        run: |
          echo "Package.json version: ${{ steps.package-json.outputs.result }}"
          echo "Cargo.toml version: ${{ steps.cargo-toml.outputs.result }}"
          echo "Tauri.conf.json version: ${{ steps.tauri-conf-json.outputs.result }}"
          if [[ "${{ steps.package-json.outputs.result }}" != "${{ steps.cargo-toml.outputs.result }}" || "${{ steps.package-json.outputs.result }}" != "${{ steps.tauri-conf-json.outputs.result }}" ]]; then
            echo "Version mismatch detected!"
            exit 1
          else
            echo "All versions are consistent."
          fi
